
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { FuzzyRiskAssessment, FlightData } from '@/services/fuzzyRiskCalculator';
import { Download, FileText } from 'lucide-react';

interface FlightReportProps {
  riskAssessment: FuzzyRiskAssessment;
  flightData: FlightData;
}

const FlightReport = ({ riskAssessment, flightData }: FlightReportProps) => {
  const generatePDFContent = () => {
    const timestamp = new Date().toLocaleString();
    
    return `
FLIGHT RISK ASSESSMENT REPORT
Generated: ${timestamp}

=== FLIGHT CONDITIONS ===
Speed: ${flightData.speed} knots
Acceleration: ${flightData.acceleration} knots/min
Temperature: ${flightData.temperature}°C
Humidity: ${flightData.humidity}%
Wind Speed: ${flightData.windSpeed} knots
Visibility: ${flightData.visibility} km

=== RISK ASSESSMENT ===
Overall Risk Level: ${riskAssessment.level.toUpperCase()}
Risk Score: ${riskAssessment.score}/100

=== FUZZY LOGIC ANALYSIS ===
Applied Rules:
${riskAssessment.fuzzyRules.map(rule => `• ${rule}`).join('\n')}

=== PARAMETER DETAILS ===
${Object.entries(riskAssessment.factors).map(([param, data]) => `
${param.toUpperCase()}:
  Value: ${data.value}
  Dominant Set: ${data.dominantSet}
  Fuzzy Memberships:
    - Low: ${(data.fuzzyValues.low * 100).toFixed(1)}%
    - Medium: ${(data.fuzzyValues.medium * 100).toFixed(1)}%
    - High: ${(data.fuzzyValues.high * 100).toFixed(1)}%
`).join('')}

=== RECOMMENDATIONS ===
Based on the current flight conditions and risk assessment, please follow all crew instructions and safety guidelines.

Report generated by Flight Risk Vision System
© 2025 Aviation Safety Analysis
    `.trim();
  };

  const downloadReport = () => {
    const content = generatePDFContent();
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `flight-report-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <FileText className="h-5 w-5" />
          Flight Report
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="bg-gray-50 p-4 rounded-lg">
          <h4 className="font-medium mb-2">Report Summary</h4>
          <div className="grid grid-cols-2 gap-4 text-sm">
            <div>
              <span className="font-medium">Risk Level:</span>
              <p className="text-muted-foreground capitalize">{riskAssessment.level}</p>
            </div>
            <div>
              <span className="font-medium">Risk Score:</span>
              <p className="text-muted-foreground">{riskAssessment.score}/100</p>
            </div>
            <div>
              <span className="font-medium">Flight Speed:</span>
              <p className="text-muted-foreground">{flightData.speed} knots</p>
            </div>
            <div>
              <span className="font-medium">Visibility:</span>
              <p className="text-muted-foreground">{flightData.visibility} km</p>
            </div>
          </div>
        </div>
        
        <div>
          <p className="text-sm text-muted-foreground mb-3">
            Download a comprehensive report of your flight's conditions and risk assessment. 
            Perfect for aviation enthusiasts or safety documentation.
          </p>
          
          <Button onClick={downloadReport} className="w-full">
            <Download className="h-4 w-4 mr-2" />
            Download Flight Report
          </Button>
        </div>
        
        <div className="text-xs text-muted-foreground">
          <p>Report includes: Flight conditions, risk analysis, fuzzy logic calculations, and safety recommendations.</p>
        </div>
      </CardContent>
    </Card>
  );
};

export default FlightReport;
